### ISSUE TITLE
Node not showing up in field ops [or any] palette[s]

### ISSUE THREAD

**Issue by blacknred0** [IBMPredictiveAnalytics/Read-JSON-File#1]
I got ....
IBM SPSS Modeler v16
IBM SPSS Modeler 'R Essentials' Plugin
R 2.15.x

I place the palette on the path per documentation, but it is not coming up.  Any recommendations?
"C:\ProgramData\IBM\SPSS\Modeler\16\CDB\readJSON.cfe"

**Comment by gfilla** [comment]
Added *.cfd file to repository for users having this issue.  Haven't seen this problem for anyone else.  Please add issue if experiencing this also.

**Comment by osnola** [comment]
Hello, I am getting the same problem; The node does not appear in any tab.
I have:
IBM SPSS Modeler v17 (Win7 x64)
R x64 3.1.0
SPSS_Modeler_REssentials_17.0_Win64
Both readJSON.cfd and readJSON.cfe are in C:\ProgramData\IBM\SPSS\Modeler\17\CDB
I have also installed the text analytics plugin, but the issue with readJSON arised before I installed that, so I don't think it is the cause.
Are there any steps (besides closing SPSS and restarting it later) that I have to take before placing the cfe file in the path?
Thank you very much.

**Comment by blacknred0** [comment]
Not sure if readJSON.cfd is causing a confusion for Modeler, but you only need "readJSON.cfe."  After adding "readJSON.cfe" on "C:\ProgramData\IBM\SPSS\Modeler\17\CDB," I didn't have an issue any more.

My problem was that I was downloading the file as HTML from GitHub, instead of raw download.

For what is worth.... make sure when you are doing all of this that Modeler is not opened.
