### ISSUE TITLE
Reading Web Data

### ISSUE THREAD

**Issue by uribaran** [IBMPredictiveAnalytics/Read-JSON-File#2]
Hi,  It would be quite useful to extend this to be able to raad web based JSON data via a URL.
Cheers

 Uri

**Comment by gfilla** [comment]
Hi,

Sorry on the delay getting back to you on this.  I am working on an enhanced version of this extension.  One enhancement will allow importing JSON from a URL.  

Thank you for the suggestion!  If you have any other suggestions or requests please let me know.

**Comment by uribaran** [comment]
Thanks Greg, that's what I call service! :)

Cheers

 Uri

PS Alteryx already do it

Uri Baran 
Technical Sales and Solutions 
IBM Analytics

Phone: 07810 154174 
E-mail: uri.baran@uk.ibm.com

**Comment by gfilla** [comment]
updated in most recent release
